### ISSUE TITLE
Harmony recs

### ISSUE THREAD

**Issue by erikstpierre** [zamu-flowerpot/zamu-flowerpot.github.io#1]
Harmony recs:

Long (100k+):
https://archiveofourown.org/works/38165668/chapters/95348221
https://archiveofourown.org/works/34429072/chapters/85681648
https://archiveofourown.org/works/35998924/chapters/89738884
https://archiveofourown.org/works/31887439/chapters/78957238
https://archiveofourown.org/works/30982961/chapters/76524524
https://archiveofourown.org/works/27085609/chapters/66136348
https://archiveofourown.org/works/35104492/chapters/87448126
https://archiveofourown.org/works/19865440/chapters/47045731

Multichaps (less than 100k):
https://archiveofourown.org/works/36997030/chapters/92306053
https://www.fanfiction.net/s/3675262/1/Stupid

Oneshot:
https://archiveofourown.org/works/35863702
https://archiveofourown.org/works/41921235
https://archiveofourown.org/works/31679084

I shall refrain from recommending my own harmony oneshot lol

**Comment by zamu-flowerpot** [comment]
Oh boy, I didn't see this after going through and sorted a bunch I did myself. 

I'll diff them and figure out which aren't there already.
